name: openmmdl  # Name of the Conda environment

channels:
  - conda-forge  # Add the conda-forge channel here

dependencies:
  - python=3.10
  - pip
  - setuptools>=61.0
  - versioningit~=2.0
  - pytest>=6.1.2
  - pytest-runner
  - numpy
  - plip
  - requests
  - rdkit
  - mdtraj
  - pdbfixer
  - openff-toolkit
  - openmmforcefields
  - cudatoolkit
  - cuda-python
  - MDAnalysis
  - pytest-shutil
  - flask
  - cairosvg
  - nglview
  - numba
  - jupyter
  # Add any additional runtime dependencies from pyproject.toml here
  # - package_name=version

  # Include the dependencies from requirements.txt
