# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/stable/config

# -- Path setup --------------------------------------------------------------

# Incase the project was not installed
import os
import sys

sys.path.insert(0, os.path.abspath(".."))

# -- Project information -----------------------------------------------------

project = "openmmdl"
copyright = (
    "2022, Valerij Talagayev, Yu Chen, Niklas Piet Doering & Leon Obendorf. Project structure based on the "
    "Computational Molecular Science Python Cookiecutter version 1.1"
)
author = "Valerij Talagayev & Yu Chen"

# The short X.Y version
version = ""
# The full version, including alpha/beta/rc tags
release = ""

# -- General configuration ---------------------------------------------------

extensions = [
    "sphinx.ext.autosummary",
    "sphinx.ext.autodoc",
    "sphinx.ext.mathjax",
    "sphinx.ext.viewcode",
    "sphinx.ext.napoleon",
    "sphinx.ext.intersphinx",
    "sphinx.ext.extlinks",
    "sphinx.ext.todo",
    "autoapi.extension",
]

autosummary_generate = True
napoleon_google_docstring = False
napoleon_use_param = False
napoleon_use_ivar = True

# -- Autodoc configuration -------------------------------------------------

# Mock heavy/optional runtime dependencies so docs can build on Read the Docs
# without requiring a full scientific stack (OpenMM/RDKit/MDAnalysis/PLIP/ProLIF/etc.).
autodoc_mock_imports = [
    "Bio",
    "Bio.PDB",
    "MDAnalysis",
    "MDAnalysis.analysis",
    "MDAnalysis.lib",
    "MDAnalysis.topology",
    "MDAnalysis.topology.guessers",
    "openmm",
    "openmm.app",
    "openmm.unit",
    "simtk",
    "simtk.openmm",
    "simtk.openmm.app",
    "simtk.openmm.unit",
    "rdkit",
    "rdkit.Chem",
    "rdkit.Chem.Draw",
    "plip",
    "plip.basic",
    "plip.exchange",
    "plip.exchange.report",
    "plip.structure",
    "plip.structure.preparation",
    "prolif",
    "mdtraj",
    "pdbfixer",
    "pdbfixer.pdbfixer",
    "openff",
    "openff.toolkit",
    "openff.toolkit.topology",
    "openmmforcefields",
    "openmmforcefields.generators",
    "PIL",
    "PIL.Image",
    "cairosvg",
    "networkx",
]

# -- AutoAPI configuration --------------------------------------------------

# AutoAPI parses source code directly (no imports required) and generates the API reference under
# docs/autoapi/ by default.
autoapi_type = "python"
autoapi_dirs = ["../openmmdl"]
autoapi_root = "autoapi"
autoapi_options = [
    "members",
    "undoc-members",
    "show-inheritance",
    "show-module-summary",
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
source_suffix = ".rst"

# The master toctree document.
master_doc = "index"

# The language for content autogenerated by Sphinx.
language = None

# List of patterns to ignore when looking for source files.
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "default"

# -- Options for HTML output -------------------------------------------------

html_theme = "renku"
html_static_path = ["_static"]

# -- Options for HTMLHelp output ---------------------------------------------

htmlhelp_basename = "openmmdldoc"

# -- Options for LaTeX output ------------------------------------------------

latex_elements = {}

latex_documents = [
    (
        master_doc,
        "openmmdl.tex",
        "openmmdl Documentation",
        author,
        "manual",
    ),
]

# -- Options for manual page output ------------------------------------------

man_pages = [(master_doc, "openmmdl", "openmmdl Documentation", [author], 1)]

# -- Options for Texinfo output ----------------------------------------------

texinfo_documents = [
    (
        master_doc,
        "openmmdl",
        "openmmdl Documentation",
        author,
        "openmmdl",
        "Preparation and Simulation of protein-ligand complexes",
        "Miscellaneous",
    ),
]

# -- Extension configuration -------------------------------------------------
# AutoAPI: exclude tests, example outputs, and script-y modules
autoapi_ignore = [
    "*migrations*",          # keep default ignore from AutoAPI docs :contentReference[oaicite:1]{index=1}

    # Generic test exclusion
    "**/tests/**",
    "**/test_*.py",
    "**/*_test.py",
    "**/*_test_*.py",

    # Your named items (directories)
    "**/6b73_simulation/**",
    "**/5wyz_simulation/**",

    # Your named items (modules/files)
    "**/test_rmsd.py",
    "**/test_utils.py",
    "**/test_figures.py",
    "**/test_barcodes.py",
    "**/test_trajectories.py",
    "**/test_highlighting.py",
    "**/test_markovchains.py",
    "**/test_bindingmodes.py",
    "**/test_preprocessing.py",
    "**/test_pharmacophore.py",
    "**/test_post_md_conversions.py",

    "**/forcefield_water.py",
    "**/post_md_conversions.py",
    "**/cleaning_procedures.py",
    "**/protein_ligand_prep.py",
    "**/forcefield_water_test.py",
    "**/protein_ligand_prep_test.py",
    "**/cleaning_procedures_test.py",
]
