name: CI-CD

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          conda env update --file environment.yml --name base 

      - name: Install package and its entry points
        run: |
          pip install .

      - name: Install linter and formatter
        run: |
          python -m pip install shyaml flake8 black black-nb flake8-nb

      - name: Run black formatter
        run: |
          black -l 99 .

      - name: Run flake8 linter
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Install pytest and run tests
        run: |
          pip install pytest pytest-cov
          pytest -vv --cov=openmmdl --cov-report=xml --cov-report=html --color=yes openmmdl/tests/
          coverage run -m pytest openmmdl/tests/
          coverage xml
          coverage report

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: coverage.xml  # Specify the path to the XML coverage report
          flags: unittests
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
